// Food Data for all categories
const foodData = {
  breakfast: [
    {
      name: "Avocado Toast",
      description: "Sourdough bread topped with smashed avocado, poached eggs, and microgreens",
      price: 12.99,
      prepTime: 15,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Belgian Waffles",
      description: "Fluffy waffles served with fresh berries, maple syrup, and whipped cream",
      price: 10.99,
      prepTime: 20,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Eggs Benedict",
      description: "English muffin topped with Canadian bacon, poached eggs, and hollandaise sauce",
      price: 14.99,
      prepTime: 25,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Greek Yogurt Parfait",
      description: "Layers of Greek yogurt, granola, fresh berries, and honey",
      price: 8.99,
      prepTime: 10,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Breakfast Burrito",
      description: "Flour tortilla filled with scrambled eggs, chorizo, cheese, and pico de gallo",
      price: 11.99,
      prepTime: 15,
      image: "/placeholder.svg?height=300&width=500",
    },
  ],
  lunch: [
    {
      name: "Grilled Chicken Caesar Salad",
      description: "Romaine lettuce, grilled chicken, parmesan cheese, croutons, and Caesar dressing",
      price: 13.99,
      prepTime: 20,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Turkey Club Sandwich",
      description: "Triple-decker sandwich with turkey, bacon, lettuce, tomato, and mayo on toasted bread",
      price: 12.99,
      prepTime: 15,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Quinoa Bowl",
      description: "Quinoa with roasted vegetables, avocado, chickpeas, and tahini dressing",
      price: 14.99,
      prepTime: 25,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Margherita Flatbread",
      description: "Thin crust flatbread with tomato sauce, fresh mozzarella, and basil",
      price: 11.99,
      prepTime: 20,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Lobster Bisque",
      description: "Creamy soup made with lobster stock, cream, and chunks of lobster meat",
      price: 15.99,
      prepTime: 30,
      image: "/placeholder.svg?height=300&width=500",
    },
  ],
  dinner: [
    {
      name: "Filet Mignon",
      description: "8oz filet served with garlic mashed potatoes and roasted asparagus",
      price: 32.99,
      prepTime: 35,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Grilled Salmon",
      description: "Wild-caught salmon with lemon butter sauce, wild rice, and seasonal vegetables",
      price: 26.99,
      prepTime: 30,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Mushroom Risotto",
      description: "Creamy Arborio rice with wild mushrooms, white wine, and parmesan cheese",
      price: 22.99,
      prepTime: 40,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Eggplant Parmesan",
      description: "Breaded eggplant slices layered with marinara sauce, mozzarella, and parmesan",
      price: 19.99,
      prepTime: 35,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Beef Bourguignon",
      description: "Slow-cooked beef stew with red wine, mushrooms, pearl onions, and herbs",
      price: 28.99,
      prepTime: 45,
      image: "/placeholder.svg?height=300&width=500",
    },
  ],
  beverages: [
    {
      name: "Signature Espresso Martini",
      description: "Vodka, coffee liqueur, and freshly brewed espresso",
      price: 12.99,
      prepTime: 5,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Berry Smoothie",
      description: "Mixed berries, banana, yogurt, and honey blended with ice",
      price: 7.99,
      prepTime: 5,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Cucumber Mint Refresher",
      description: "Muddled cucumber and mint with lime juice, simple syrup, and soda water",
      price: 8.99,
      prepTime: 8,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Aged Old Fashioned",
      description: "Bourbon, bitters, sugar, and orange peel",
      price: 14.99,
      prepTime: 5,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Matcha Latte",
      description: "Ceremonial grade matcha whisked with steamed milk",
      price: 6.99,
      prepTime: 5,
      image: "/placeholder.svg?height=300&width=500",
    },
  ],
  dessert: [
    {
      name: "Chocolate Lava Cake",
      description: "Warm chocolate cake with a molten center, served with vanilla ice cream",
      price: 9.99,
      prepTime: 15,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "New York Cheesecake",
      description: "Classic cheesecake with graham cracker crust and berry compote",
      price: 8.99,
      prepTime: 10,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Tiramisu",
      description: "Layers of coffee-soaked ladyfingers and mascarpone cream dusted with cocoa",
      price: 10.99,
      prepTime: 10,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Crème Brûlée",
      description: "Vanilla custard with a caramelized sugar crust",
      price: 9.99,
      prepTime: 10,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Apple Tart",
      description: "Buttery pastry crust filled with cinnamon-spiced apples and served with caramel sauce",
      price: 8.99,
      prepTime: 15,
      image: "/placeholder.svg?height=300&width=500",
    },
  ],
  indian: [
    {
      name: "Butter Chicken",
      description: "Tender chicken in a rich tomato and butter sauce, served with basmati rice",
      price: 18.99,
      prepTime: 30,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Vegetable Biryani",
      description: "Fragrant basmati rice cooked with mixed vegetables and aromatic spices",
      price: 16.99,
      prepTime: 35,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Palak Paneer",
      description: "Cottage cheese cubes in a creamy spinach sauce with Indian spices",
      price: 15.99,
      prepTime: 25,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Lamb Rogan Josh",
      description: "Slow-cooked lamb in a rich Kashmiri spice blend",
      price: 21.99,
      prepTime: 40,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Garlic Naan",
      description: "Soft flatbread topped with garlic and butter, baked in a tandoor oven",
      price: 4.99,
      prepTime: 15,
      image: "/placeholder.svg?height=300&width=500",
    },
  ],
  italian: [
    {
      name: "Spaghetti Carbonara",
      description: "Spaghetti with pancetta, egg, pecorino cheese, and black pepper",
      price: 17.99,
      prepTime: 25,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Margherita Pizza",
      description: "Thin crust pizza with tomato sauce, fresh mozzarella, and basil",
      price: 15.99,
      prepTime: 20,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Osso Buco",
      description: "Braised veal shanks with vegetables, white wine, and gremolata",
      price: 29.99,
      prepTime: 45,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Risotto ai Funghi",
      description: "Creamy risotto with wild mushrooms, white wine, and parmesan",
      price: 19.99,
      prepTime: 30,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Italian Tiramisu",
      description: "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream",
      price: 9.99,
      prepTime: 15,
      image: "/placeholder.svg?height=300&width=500",
    },
  ],
  chinese: [
    {
      name: "Kung Pao Chicken",
      description: "Stir-fried chicken with peanuts, vegetables, and chili peppers",
      price: 16.99,
      prepTime: 25,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Peking Duck",
      description: "Roasted duck served with thin pancakes, scallions, cucumber, and hoisin sauce",
      price: 32.99,
      prepTime: 40,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Mapo Tofu",
      description: "Soft tofu in a spicy sauce with minced pork and Sichuan peppercorns",
      price: 14.99,
      prepTime: 20,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Dim Sum Platter",
      description: "Assortment of steamed dumplings, buns, and small bites",
      price: 18.99,
      prepTime: 30,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Hot and Sour Soup",
      description: "Spicy and tangy soup with tofu, mushrooms, bamboo shoots, and egg",
      price: 8.99,
      prepTime: 15,
      image: "/placeholder.svg?height=300&width=500",
    },
  ],
  mexican: [
    {
      name: "Carne Asada Tacos",
      description: "Grilled steak tacos with onions, cilantro, and salsa verde",
      price: 14.99,
      prepTime: 20,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Chicken Enchiladas",
      description: "Corn tortillas filled with shredded chicken, topped with enchilada sauce and cheese",
      price: 16.99,
      prepTime: 30,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Chiles Rellenos",
      description: "Poblano peppers stuffed with cheese, battered and fried, served with tomato sauce",
      price: 17.99,
      prepTime: 35,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Guacamole & Chips",
      description: "Fresh avocado dip with tomatoes, onions, cilantro, and lime, served with tortilla chips",
      price: 9.99,
      prepTime: 10,
      image: "/placeholder.svg?height=300&width=500",
    },
    {
      name: "Mole Poblano",
      description: "Chicken in a rich sauce made with chocolate, chiles, and spices, served with rice",
      price: 19.99,
      prepTime: 40,
      image: "/placeholder.svg?height=300&width=500",
    },
  ],
}
